CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;

SELECT PostGIS_version();

CREATE TYPE "BookCategory" AS ENUM ('NOVEL', 'COMIC');
CREATE TYPE "Genre" AS ENUM ('HORROR', 'COMEDY', 'ACTION', 'GORE', 'SLICE_OF_LIFE', 'ROMANCE', 'MYSTERY', 'PSYCOLOGY', 'FANTASY', 'MATURE');
CREATE TYPE "BeverageCategory" AS ENUM ('COFFEE', 'JUICE', 'MILKSHAKE', 'MINERAL');
CREATE TYPE "OrderType" AS ENUM ('DELIVERY', 'PICKUP');
CREATE TYPE "PaymentMethod" AS ENUM ('TRANSFER', 'COD');
CREATE TYPE "PaymentStatus" AS ENUM ('UNPAID', 'PAID', 'FAILED');
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'ASSIGNED', 'PROCESSING', 'COMPLETED', 'CANCELLED');
CREATE TYPE "ItemType" AS ENUM ('BOOK', 'BEVERAGE');
CREATE TYPE "TargetType" AS ENUM ('DRIVER', 'BOOK');
CREATE TYPE "DiscountType" AS ENUM ('PERCENTAGE', 'FIXED');

GRANT ALL PRIVILEGES ON DATABASE fusion_heart_db TO fusionheart;