FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm install -g nodemon
RUN npm install -g tsx

EXPOSE 3000

CMD ["nodemon", "--legacy-watch", "--exec", "tsx", "src/server.ts"]